homeURL = "/"
DefaultContentLanguage = "en"
pygmentsUseClassic = false
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
pygmentsUseClasses = true

[params]
  menuNames = ["main","footer","services"]
  homeURL = "/"

[languages]
  [languages.en]
    baseURL = 'https://factory.report'
  productionURL = "https://factory.report"
    LanguageName = "English"
    weight = 1
    [languages.en.params]
      siteName = "FACTORY REPORT"
  [languages.cs]
    baseURL = 'https://vyrobni.report'
    productionURL = "https://vyrobni.report"
    LanguageName = "Česky"
    weight = 2
    [languages.cs.params]
      siteName = "VÝROBNÍ REPORT"

[[languages.en.menu.main]]
  url    = "#top"
  name   = "Home"
  pre = "sticky-top"
  post = ""
  weight = 1

[[languages.en.menu.main]]
  url    = "#how"
  name   = "How it works"
  pre = "sticky-how"
  post = ""
  weight = 5

[[languages.en.menu.main]]
  url    = "#pricelist"
  name   = "Pricing"
  pre = "sticky-pricelist"
  post = ""
  weight = 15

[[languages.en.menu.main]]
  url    = "#meeting"
  name   = "Contact"
  pre = "sticky-meeting"
  post = ""
  weight = 25

[[languages.cs.menu.main]]
  url    = "#top"
  name   = "Úvod"
  pre = "sticky-top"
  post = ""
  weight = 1

[[languages.cs.menu.main]]
  url    = "#how"
  name   = "Jak to funguje"
  pre = "sticky-how"
  post = ""
  weight = 5

[[languages.cs.menu.main]]
  url    = "#pricelist"
  name   = "Ceny"
  pre = "sticky-pricelist"
  post = ""
  weight = 15

[[languages.cs.menu.main]]
  url    = "#meeting"
  name   = "Kontakt"
  pre = "sticky-meeting"
  post = ""
  weight = 25

[blackfriday]
smartypants = false

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[taxonomies]
  tag = "tags"
  category= "categories"

[outputs]
        home = [ "HTML", "JSON"]
        page = [ "HTML"]
